spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 402783451794-u7rkm04rveeonmgii4ckltqlnl673sf9.apps.googleusercontent.com
            client-secret: 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
            scope:
              - email
              - profile
            redirect-uri: http://localhost:8080/login/oauth2/code/google
          # Uncomment if Kakao settings are needed
          # kakao:
          #   client-id: 4c35ca8aa57dce8c012fbd79aaa84c16
          #   redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
          #   client-authentication-method: client_secret_post
          #   authorization-grant-type: authorization_code
          #   scope:
          #     - profile_nickname
          #     - account_email
          #   client-name: Kakao
          # Uncomment if Naver settings are needed
          # naver:
          #   client-id: uKiP7WPNBZBkt2l_R87L
          #   client-secret: bMK2yjMkyl
          #   scope:
          #     - name
          #     - email
          #     - profile_image
          #   client-name: Naver
          #   authorization-grant-type: authorization_code
          #   redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
        provider:
          google:
            authorization-uri: https://accounts.google.com/o/oauth2/v2/auth
            token-uri: https://oauth2.googleapis.com/token
            user-info-uri: https://www.googleapis.com/oauth2/v3/userinfo
            user-name-attribute: sub
          # Uncomment if Kakao settings are needed
          # kakao:
          #   authorization-uri: https://kauth.kakao.com/oauth/authorize
          #   token-uri: https://kauth.kakao.com/oauth/token
          #   user-info-uri: https://kapi.kakao.com/v2/user/me
          #   user-name-attribute: id
          # Uncomment if Naver settings are needed
          # naver:
          #   authorization-uri: https://nid.naver.com/oauth2.0/authorize
          #   token-uri: https://nid.naver.com/oauth2.0/token
          #   user-info-uri: https://openapi.naver.com/v1/nid/me
          #   user-name-attribute: response
