spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 402783451794-u7rkm04rveeonmgii4ckltqlnl673sf9.apps.googleusercontent.com
            client-secret: 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
            scope:
              - email
              - profile
            redirect-uri: http://localhost:8080/login/oauth2/code/google
          kakao:
            client-id: ada59583cab77aa3606c7a986e7f8e9b
            # client-secret: :D9p8AYFlDVXeICxsmHAClHMDkxVi4jbn
            client-authentication-method: client_secret_post
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:8080/login/oauth2/code/kakao
            scope:
              - profile_nickname
              - account_email
            client-name: Kakao
          naver:
            client-id: suHZrf4CfRq3ceMv4n2G
            client-secret: 6NpSwYTpo5
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:8080/login/oauth2/code/naver
            scope:
              - name
              - email
            client-name: Naver
        provider:
          google:
            authorization-uri: https://accounts.google.com/o/oauth2/v2/auth
            token-uri: https://oauth2.googleapis.com/token
            user-info-uri: https://www.googleapis.com/oauth2/v3/userinfo
            user-name-attribute: sub
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response # 네이버가 JSON 반환 시 response 키에 회원 정보 포함
